### ISSUE TITLE
. changes huawei

### ISSUE THREAD

**Issue by EloYGomeZ** [moetayuko/android_kernel_huawei_msm8916#1]
because not added as changes huawei???

**Comment by moetayuko** [comment]
i'm shocked when i saw you've use the wrong CAF tag.
the original tag doesn't exist on CAF!
i use an old and cherry-pick changes from upstream so that i can see what exactly huawei did.
huawei changes are on my local repo

**Comment by moetayuko** [comment]
i do it slowly because of time limit

**Comment by EloYGomeZ** [comment]
But so is much harder to add changes huawei
