### ISSUE TITLE
official 5.1 kernel source

### ISSUE THREAD

**Issue by moetayuko** [moetayuko/android_kernel_huawei_msm8916#2]
@Blefish @surdupetru
Huawei released official 5.1 kernel source for honor 4x, based on CAF LA.BR.1.1.3.c12-01400-8x16.0
http://download-c.huawei.com/download/downloadCenter?downloadId=54504&version=169737&siteCode=cn

But they changed a lot on QC baseline, I was shocked after typing "git status", it's a big diff.
If you have time you can try to get it boot

**Comment by moetayuko** [comment]
If you need I can provide link for official 5.1 release

Now I'm too busy and keep nubia z9 max for daily use, so don't have time with huawei devices.

**Comment by weimzh** [comment]
Official 6.0 kernel source is also released at:
http://download-c.huawei.com/download/downloadCenter?downloadId=81728&version=324293&siteCode=cn

**Comment by rtammekivi** [comment]
ROM available somewhere too? I'd like to dump the /system, maybe update baseband too?

**Comment by weimzh** [comment]
it's only available via the official system upgrade app, however someone extracted the complete UPDATE.APP and posted them in huawei official forum:
http://club.huawei.com/thread-10322876-1-1.html

荣耀畅玩4X 全网通（Che1-CL20）
链接: pan.baidu.com/s/1c22Z8p6 密码: 7j9p
md5:D59BE5608FD660F08C89C10EDECBF672

荣耀畅玩4X 电信版（Che1-CL10）
链接: pan.baidu.com/s/1pLF4yEJ 密码: 1pq3
md5:FB22BA1893216DAB4AC91E8EE3841E19

荣耀畅玩4X 移动高配版（Che2-TL00）
链接: pan.baidu.com/s/1gfqcrzd 密码: zr5u
md5:7B5BBB90BFC82A728FA0091543C44E09

荣耀畅玩4X 联通高配版（Che2-UL00）
链接: pan.baidu.com/s/1mhLzUOC 密码: ybn6
md5:7B5BBB90BFC82A728FA0091543C44E09

荣耀畅玩4X 移动定制版 高配（Che2-TL00M）
链接: pan.baidu.com/s/1jHCa6ME 密码: vuu3
md5:7B5BBB90BFC82A728FA0091543C44E09

荣耀畅玩4X 联通定制版 高配（Che2-UL00）
链接: pan.baidu.com/s/1dF4Z0tz 密码: b6jy
md5:7B5BBB90BFC82A728FA0091543C44E09

荣耀畅玩4X 移动高配版（CHE-TL00）
链接: pan.baidu.com/s/1jIe0PxG 密码: v2mu
md5:95B7294D21470B0662EA7BB4FA65B6BB

荣耀畅玩4X 移动定制版 高配（CHE-TL00H）
链接: pan.baidu.com/s/1pLEi11x 密码: cabu
md5:95B7294D21470B0662EA7BB4FA65B6BB

looks like they switched to aarch64 though, so it's not likely to be compatible with cyanogenmod (which is still 32-bit).

**Comment by rtammekivi** [comment]
Yes, we are doing 32-bit builds because 64 bit requires bootloader compatibility. But it seems like 64 bit is optimal on devices with more than 1GB of RAM as it increases memory pressure.
